--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/13/2022 7:08:10 AM
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE stock_database;

--
-- Drop procedure `Proc_GetCommentByID`
--
DROP PROCEDURE IF EXISTS Proc_GetCommentByID;

--
-- Drop procedure `Proc_GetCommentByPostID`
--
DROP PROCEDURE IF EXISTS Proc_GetCommentByPostID;

--
-- Drop procedure `Proc_GetUserByID`
--
DROP PROCEDURE IF EXISTS Proc_GetUserByID;

--
-- Drop table `comment`
--
DROP TABLE IF EXISTS comment;

--
-- Drop procedure `Proc_GetPostByID`
--
DROP PROCEDURE IF EXISTS Proc_GetPostByID;

--
-- Drop procedure `Proc_GetPostByUserID`
--
DROP PROCEDURE IF EXISTS Proc_GetPostByUserID;

--
-- Drop table `post`
--
DROP TABLE IF EXISTS post;

--
-- Drop procedure `Proc_GetSymbolByUserID`
--
DROP PROCEDURE IF EXISTS Proc_GetSymbolByUserID;

--
-- Drop table `symbol`
--
DROP TABLE IF EXISTS symbol;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE stock_database;

--
-- Create table `user`
--
CREATE TABLE user (
  UserID varchar(36) NOT NULL DEFAULT '',
  UserName varchar(255) DEFAULT NULL,
  Password varchar(255) DEFAULT NULL,
  Avatar varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `symbol`
--
CREATE TABLE symbol (
  SymbolID varchar(36) NOT NULL DEFAULT '',
  UserID varchar(255) DEFAULT NULL,
  SymbolName varchar(255) DEFAULT NULL,
  ShortName varchar(255) DEFAULT NULL,
  PRIMARY KEY (SymbolID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE symbol
ADD CONSTRAINT FK_symbol_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

DELIMITER $$

--
-- Create procedure `Proc_GetSymbolByUserID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetSymbolByUserID (IN $UserID varchar(36))
BEGIN
  SELECT
    *
  FROM symbol s
  WHERE s.UserID = $UserID;
END
$$

DELIMITER ;

--
-- Create table `post`
--
CREATE TABLE post (
  PostID varchar(36) NOT NULL DEFAULT '',
  UserID varchar(36) DEFAULT NULL,
  Content varchar(255) DEFAULT NULL,
  ImgUrl varchar(255) DEFAULT NULL,
  CommentNumber int DEFAULT NULL,
  LikeNumber int DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  PRIMARY KEY (PostID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE post
ADD CONSTRAINT FK_post_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

DELIMITER $$

--
-- Create procedure `Proc_GetPostByUserID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetPostByUserID (IN $UserID varchar(36))
BEGIN
  SELECT
    *
  FROM post p
  WHERE p.UserID = $UserID;
END
$$

--
-- Create procedure `Proc_GetPostByID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetPostByID (IN $PostID varchar(36))
BEGIN
  SELECT
    *
  FROM post p
  WHERE p.PostID = $PostID;
END
$$

DELIMITER ;

--
-- Create table `comment`
--
CREATE TABLE comment (
  CommentID varchar(36) NOT NULL DEFAULT '',
  PostID varchar(36) DEFAULT NULL,
  UserID varchar(36) DEFAULT NULL,
  Content varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  PRIMARY KEY (CommentID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT FK_comment_PostID FOREIGN KEY (PostID)
REFERENCES post (PostID);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT FK_comment_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

DELIMITER $$

--
-- Create procedure `Proc_GetUserByID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetUserByID (IN $UserID varchar(36))
BEGIN
  SELECT
    *
  FROM user u
  WHERE u.UserID = $UserID;
END
$$

--
-- Create procedure `Proc_GetCommentByPostID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetCommentByPostID (IN $PostID varchar(36))
BEGIN
  SELECT
    *
  FROM comment c
  WHERE c.PostID = $PostID;
END
$$

--
-- Create procedure `Proc_GetCommentByID`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetCommentByID (IN $CommentID varchar(36))
BEGIN
  SELECT
    *
  FROM comment c
  WHERE c.CommentID = $CommentID;
END
$$

DELIMITER ;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'user1', '12345678', NULL, '2022-12-11 00:00:00'),
('e5bca2fd-7a71-11ed-b16b-d8bbc1b0794d', 'user2', '12345678', NULL, '2022-12-13 00:00:00');

-- 
-- Dumping data for table post
--
INSERT INTO post VALUES
('7e701e13-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'skhdjshds', NULL, 8, 100, '2022-12-13 00:00:00'),
('866e86ac-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'rffeeec', NULL, 81, 1000, '2022-12-13 00:00:00'),
('880c35f0-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'rghbyjuyh', NULL, 65, 434, '2022-12-13 00:00:00'),
('88774d1d-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'hyikjnyb', NULL, 32, 565, '2022-12-13 00:00:00');

-- 
-- Dumping data for table symbol
--
-- Table stock_database.symbol does not contain any data (it is empty)

-- 
-- Dumping data for table comment
--
INSERT INTO comment VALUES
('20f42bfa-7242-4ae1-9d02-167041c50b1c', '866e86ac-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'hello', '2022-12-13 06:32:38'),
('68d453bc-4813-40f5-ab20-3046fccedc49', '7e701e13-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'string', '2022-12-13 06:31:56'),
('fa628279-1ca5-41ef-b127-978de69251f5', '7e701e13-7a72-11ed-b16b-d8bbc1b0794d', 'bac7fd1b-7916-11ed-b16b-d8bbc1b0794d', 'hello', '2022-12-13 06:32:20');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;